#编号服务配置文件

#Host="http://120.78.195.103" #外网ip
#Host="http://172.18.22.36" #host内网
#Port="9898" #端口

# ********测试**********
#Host="http://39.108.80.66" #host内网
#Port="9897" #端口
# ********测试end*******
# ********开发**********
#Host="http://192.168.83.79"
#Port="9897"
# ********开发end*******

# ********张鑫**********
#Host="http://192.168.83.164"
#Port="9897"
# ********张鑫end*********
#********************请求方法配置**************************
AddOrder="addOrder"
