// Code generated by protoc-gen-go. DO NOT EDIT.
// source: obj.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 职位对象
type Job struct {
	JobAddress string `protobuf:"bytes,1,opt,name=JobAddress" json:"JobAddress,omitempty"`
	Role       uint32 `protobuf:"varint,2,opt,name=Role" json:"Role,omitempty"`
	Count      uint32 `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	Radio      uint64 `protobuf:"varint,4,opt,name=Radio" json:"Radio,omitempty"`
	Company    string `protobuf:"bytes,5,opt,name=Company" json:"Company,omitempty"`
	TimeStamp  int64  `protobuf:"varint,6,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	HasApply   bool   `protobuf:"varint,7,opt,name=HasApply" json:"HasApply,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Job) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

func (m *Job) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Job) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Job) GetRadio() uint64 {
	if m != nil {
		return m.Radio
	}
	return 0
}

func (m *Job) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Job) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Job) GetHasApply() bool {
	if m != nil {
		return m.HasApply
	}
	return false
}

// 工作单位
type Unit struct {
	Role      int32  `protobuf:"varint,1,opt,name=Role" json:"Role,omitempty"`
	Company   string `protobuf:"bytes,2,opt,name=Company" json:"Company,omitempty"`
	Location  string `protobuf:"bytes,3,opt,name=Location" json:"Location,omitempty"`
	StartTime uint32 `protobuf:"varint,4,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime   uint32 `protobuf:"varint,5,opt,name=EndTime" json:"EndTime,omitempty"`
}

func (m *Unit) Reset()                    { *m = Unit{} }
func (m *Unit) String() string            { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()               {}
func (*Unit) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Unit) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Unit) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Unit) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Unit) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Unit) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

// 排班
type Schedule struct {
	Jobaddr     string `protobuf:"bytes,1,opt,name=Jobaddr" json:"Jobaddr,omitempty"`
	Jobs        []*Job `protobuf:"bytes,2,rep,name=Jobs" json:"Jobs,omitempty"`
	TimeStamp   int64  `protobuf:"varint,3,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	CompanyName string `protobuf:"bytes,4,opt,name=CompanyName" json:"CompanyName,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Schedule) GetJobaddr() string {
	if m != nil {
		return m.Jobaddr
	}
	return ""
}

func (m *Schedule) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *Schedule) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Schedule) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

// 申请人信息
type ScheduleStaff struct {
	StaffAddr string `protobuf:"bytes,1,opt,name=StaffAddr" json:"StaffAddr,omitempty"`
	Role      uint64 `protobuf:"varint,2,opt,name=Role" json:"Role,omitempty"`
	Ratio     uint64 `protobuf:"varint,3,opt,name=Ratio" json:"Ratio,omitempty"`
}

func (m *ScheduleStaff) Reset()                    { *m = ScheduleStaff{} }
func (m *ScheduleStaff) String() string            { return proto.CompactTextString(m) }
func (*ScheduleStaff) ProtoMessage()               {}
func (*ScheduleStaff) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ScheduleStaff) GetStaffAddr() string {
	if m != nil {
		return m.StaffAddr
	}
	return ""
}

func (m *ScheduleStaff) GetRole() uint64 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *ScheduleStaff) GetRatio() uint64 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

// 订单信息
type Order struct {
	Table      uint32  `protobuf:"varint,1,opt,name=Table" json:"Table,omitempty"`
	TimeStamp  int64   `protobuf:"varint,2,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	Money      float64 `protobuf:"fixed64,3,opt,name=Money" json:"Money,omitempty"`
	OrderId    string  `protobuf:"bytes,4,opt,name=OrderId" json:"OrderId,omitempty"`
	Content    string  `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	GetMoney_  float64 `protobuf:"fixed64,6,opt,name=GetMoney" json:"GetMoney,omitempty"`
	JobAddress string  `protobuf:"bytes,7,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Order) GetTable() uint32 {
	if m != nil {
		return m.Table
	}
	return 0
}

func (m *Order) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Order) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Order) GetGetMoney_() float64 {
	if m != nil {
		return m.GetMoney_
	}
	return 0
}

func (m *Order) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "protocol.Job")
	proto.RegisterType((*Unit)(nil), "protocol.Unit")
	proto.RegisterType((*Schedule)(nil), "protocol.Schedule")
	proto.RegisterType((*ScheduleStaff)(nil), "protocol.scheduleStaff")
	proto.RegisterType((*Order)(nil), "protocol.Order")
}

func init() { proto.RegisterFile("obj.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xe5, 0x26, 0x69, 0x93, 0x59, 0xe5, 0x62, 0xed, 0xc1, 0x5a, 0x21, 0x14, 0x72, 0xca,
	0xa9, 0x07, 0x78, 0x82, 0xb2, 0x42, 0x40, 0xc4, 0x1f, 0xc9, 0x5d, 0xc4, 0xd9, 0xa9, 0x5d, 0x11,
	0xd4, 0x7a, 0xa2, 0xc4, 0x7b, 0xe8, 0x8d, 0x1b, 0xbc, 0x12, 0x47, 0xde, 0x0c, 0x79, 0xe2, 0x34,
	0x6d, 0x4f, 0xc9, 0xef, 0x1b, 0x69, 0xe6, 0x9b, 0x6f, 0x0c, 0x19, 0x36, 0x3f, 0xd7, 0x5d, 0x8f,
	0x0e, 0x79, 0x4a, 0x9f, 0x1d, 0x1e, 0xca, 0xbf, 0x0c, 0xa2, 0x1a, 0x1b, 0xfe, 0x12, 0xa0, 0xc6,
	0x66, 0xa3, 0x75, 0x6f, 0x86, 0x41, 0xb0, 0x82, 0x55, 0x99, 0xbc, 0x50, 0x38, 0x87, 0x58, 0xe2,
	0xc1, 0x88, 0x45, 0xc1, 0xaa, 0x5c, 0xd2, 0x3f, 0xbf, 0x87, 0xe4, 0x11, 0x9f, 0xad, 0x13, 0x11,
	0x89, 0x23, 0x78, 0x55, 0x2a, 0xdd, 0xa2, 0x88, 0x0b, 0x56, 0xc5, 0x72, 0x04, 0x2e, 0x60, 0xf5,
	0x88, 0xc7, 0x4e, 0xd9, 0x93, 0x48, 0xa8, 0xf9, 0x84, 0xfc, 0x05, 0x64, 0x4f, 0xed, 0xd1, 0x6c,
	0x9d, 0x3a, 0x76, 0x62, 0x59, 0xb0, 0x2a, 0x92, 0xb3, 0xc0, 0x1f, 0x20, 0xfd, 0xa0, 0x86, 0x4d,
	0xd7, 0x1d, 0x4e, 0x62, 0x55, 0xb0, 0x2a, 0x95, 0x67, 0x2e, 0xff, 0x30, 0x88, 0xbf, 0xd9, 0xd6,
	0x9d, 0xcd, 0x79, 0xdb, 0x49, 0x30, 0x77, 0x31, 0x70, 0x71, 0x3d, 0xf0, 0x01, 0xd2, 0x4f, 0xb8,
	0x53, 0xae, 0x45, 0x4b, 0xce, 0x33, 0x79, 0x66, 0x6f, 0x66, 0xeb, 0x54, 0xef, 0xbc, 0x01, 0x5a,
	0x20, 0x97, 0xb3, 0xe0, 0x7b, 0xbe, 0xb3, 0x9a, 0x6a, 0x09, 0xd5, 0x26, 0x2c, 0x7f, 0x33, 0x48,
	0xb7, 0xbb, 0x1f, 0x46, 0x3f, 0x8f, 0xa3, 0x6b, 0x6c, 0x94, 0xd6, 0x7d, 0x08, 0x72, 0x42, 0xfe,
	0x0a, 0xe2, 0x1a, 0x9b, 0x41, 0x2c, 0x8a, 0xa8, 0xba, 0x7b, 0x9d, 0xaf, 0xa7, 0x33, 0xac, 0x6b,
	0x6c, 0x24, 0x95, 0xae, 0xe3, 0x88, 0x6e, 0xe3, 0x28, 0xe0, 0x2e, 0xac, 0xf1, 0x45, 0x05, 0x87,
	0x99, 0xbc, 0x94, 0xca, 0xef, 0x90, 0x0f, 0xc1, 0xc8, 0xd6, 0xa9, 0xfd, 0x3e, 0xac, 0xb4, 0xdf,
	0x6f, 0x66, 0x3f, 0xb3, 0x70, 0x75, 0xd7, 0x78, 0xbe, 0xab, 0xf4, 0x71, 0xd0, 0x78, 0xba, 0xa0,
	0x6b, 0xb1, 0xfc, 0xc7, 0x20, 0xf9, 0xda, 0x6b, 0xd3, 0xfb, 0xfa, 0x93, 0x6a, 0x42, 0xde, 0xb9,
	0x1c, 0xe1, 0xda, 0xf8, 0xe2, 0xd6, 0xf8, 0x3d, 0x24, 0x9f, 0xd1, 0x9a, 0x13, 0xf5, 0x64, 0x72,
	0x04, 0x9f, 0x14, 0xb5, 0xfc, 0xa8, 0xc3, 0x2a, 0x13, 0x8e, 0xe7, 0xb3, 0xce, 0x58, 0x37, 0xbf,
	0x17, 0x42, 0x7f, 0xbe, 0xf7, 0xc6, 0x8d, 0xcd, 0x96, 0xd4, 0xec, 0xcc, 0x37, 0xaf, 0x78, 0x75,
	0xfb, 0x8a, 0xdf, 0x46, 0xbf, 0x18, 0x6b, 0x96, 0x94, 0xfa, 0x9b, 0xff, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x84, 0x01, 0x83, 0x10, 0x03, 0x00, 0x00,
}
