# ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grm-searcher
  namespace: titangrm-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grm-searcher
  template:
    metadata:
      labels:
        app: grm-searcher
    spec:
      containers:
      - name: grm-searcher
        image: 192.168.1.149:5000/titan-grm
        imagePullPolicy: Always
        volumeMounts:
          - name: titangrm-config
            mountPath: /opt/titangrm/config
        env:
        - name: GRM_SERVER_ADDRESS
          value: :8080
        - name: GRM_SERVER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GRM_REGISTRY_ADDRESS
          value: consul-ttmi68.consul-ttmi68:8500
        command: ["/usr/local/bin/titan-grm"]
        args:
          - searcher
          - "-registry_address"
          - $(GRM_REGISTRY_ADDRESS)
          - "-server_namespace"
          - $(GRM_SERVER_NAMESPACE)
        ports:
        - containerPort: 8080
      volumes:
        - name: titangrm-config
          persistentVolumeClaim:
            claimName: titangrm-config-pvc

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: grm-searcher
  namespace: titangrm-dev
spec:
  ports:
  - port: 8336
    targetPort: 8080
  selector:
    app: grm-searcher

---
# NodePort
apiVersion: v1
kind: Service
metadata:
  name: grm-searcher-nodeport
  namespace: titangrm-dev
spec:
  type: NodePort
  ports:
  - port: 8336
    targetPort: 8080
    #nodePort: 30001
  selector:
    app: grm-searcher
