# ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: storage-manager
  namespace: titangrm-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-manager
  template:
    metadata:
      labels:
        app: storage-manager
    spec:
      containers:
      - name: storage-manager
        image: 192.168.1.149:5000/titan-grm
        imagePullPolicy: Always
        volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
            readOnly: true
          - name: titangrm-config
            mountPath: /opt/titangrm/config
          - name: titangrm-data
            mountPath: /opt/titangrm/data
        env:
        - name: GRM_SERVER_ADDRESS
          value: :8080
        - name: GRM_SERVER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GRM_REGISTRY_ADDRESS
          value: consul-ttmi68.consul-ttmi68:8500
        command: ["/usr/local/bin/titan-grm"]
        args:
          - storage-manager
          - "-registry_address"
          - $(GRM_REGISTRY_ADDRESS)
          - "-server_namespace"
          - $(GRM_SERVER_NAMESPACE)
        ports:
        - containerPort: 8080
      volumes:
        - name: tz-config
          hostPath:
             path: /etc/localtime
        - name: titangrm-config
          persistentVolumeClaim:
            claimName: titangrm-config-pvc
        - name: titangrm-data
          persistentVolumeClaim:
            claimName: titangrm-data-pvc

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: storage-manager
  namespace: titangrm-dev
spec:
  ports:
  - port: 8445
    targetPort: 8080
  selector:
    app: storage-manager

---
# NodePort
apiVersion: v1
kind: Service
metadata:
  name: storage-manager-nodeport
  namespace: titangrm-dev
spec:
  type: NodePort
  ports:
  - port: 8443
    targetPort: 8080
    #nodePort: 30001
  selector:
    app: storage-manager
