Operate_timeout = 10                  # 用户操作超时，单位秒
LocalAddress   = "192.168.83.79"     # 本机地址
ApiAddress     = "192.168.83.79"       # api地址
EthAddress     = "39.108.80.66:8546"  # Eth地址
FinanceOrderSvcAddress = "192.168.83.79" 		  # 三方支付地址

WebPort         = "7778"             # 端口
ApiPort         = "8082"             # 端口
FinanceOrderSvcPort    = "9898"             # 端口

FinanceOrderSvcAppId = "10000" 		  #获取订单列表需要的AppId

PaySwitch 		= 0 				  #是否转账开关

AutoTransferLimit = 10000.0			  #自动转账金额

OnchainTimeLimit 	= 7200 			  #重试上链时间

OnchainNumber 	= 10 				  #重试上链次数

FeesSwitch 		= 0 				  #是否收取手续费

TransferUserLimitMoneyTime = 0 		  #给余额累加用户转账时间

TransferUserLimitMoney = 0.1 		  #给余额累加用户转账额度

IsQueryTradeDetails = 0				  #是否查询交易详情

TimeTicker1 	= 10                  #定时从三方支付获取流水信息，存储redis
TimeTicker2 	= 10				  #定时查询获取详情失败的账单，重新获取账单详情
TimeTicker3 	= 10                  #定时获取未做上链操作或者上链失败的流水，进行上链操作
TimeTicker4 	= 10                  #定时获取之前未上链完成的流水，看当前是否已上链
TimeTicker5 	= 10                  #定时从数据库获取未分账信息，开始分账
TimeTicker6 	= 10                  #定时查询正在上链的分账信息，是否上链成功
TimeTicker7 	= 10                  #定时查询上链失败或者未上链的分账信息，重新上链
TimeTicker8 	= 10                  #定点获取用户累积未转账的money，准备转账

MysqlStr="isbs:isbs*2018@tcp(rm-wz961aqvp3aq3gs334o.mysql.rds.aliyuncs.com:3306)/finance?charset=utf8&parseTime=true&loc=Local"

RedisAddr		= "192.168.83.79:6379"
RedisPasswd 	= ""

#FinanceAddress  = "0x35e803774176607ad7794170B251586534eCB05A"
#FinanceKeyStore = "{\"address\":\"35e803774176607ad7794170b251586534ecb05a\",\"crypto\":{\"cipher\":\"aes-128-ctr\",\"ciphertext\":\"949d7b3e0bf7251d49a1009165f648297c276c4b801da3eb2eeed69b8c23a29e\",\"cipherparams\":{\"iv\":\"fb191092ae4f573eea9ecd37bc3ad558\"},\"kdf\":\"scrypt\",\"kdfparams\":{\"dklen\":32,\"n\":262144,\"p\":1,\"r\":8,\"salt\":\"f8902fe8364ce84067f934a62aa797bcf99b90c094af97613ec7e37df55b3a42\"},\"mac\":\"455acd4a8fba6335c18db670eccba5c817ff85c85576d499c1c3185518a2ac70\"},\"id\":\"a96b2f2e-1247-4939-afd3-bbf50a54706b\",\"version\":3}"
#FinancePhrase   = "1"

FinanceAddress  = "0x56a58d378fd5647de22bf10007ab2f49e47d83b7"
FinanceKeyStore = '{"address":"56a58d378fd5647de22bf10007ab2f49e47d83b7","crypto":{"cipher":"aes-128-ctr","ciphertext":"01b960ea11abb9baa2d9f5e4f8cec0eaaa2a6165f6a3c63b1fb3a767e86ad729","cipherparams":{"iv":"20f30ca3334be401de850a6fd912aa4f"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"2e219cc58e1468cc95863f62ce9d1bf5bbdec467f13ed4ecd2bc996f11c56822"},"mac":"6faf19ee181fbfd076a446854e2348020408b34e120824edc69085f2306bfa26"},"id":"44e95601-9851-422e-ae00-c0a481436fe6","version":3}'
FinancePhrase   = "dev3_apple1"
