// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	api.proto
	config.proto
	obj.proto
	status.proto

It has these top-level messages:
	Req
	Resp
	ReqGetEthBalance
	RespGetEthBalance
	ReqRegister
	RespRegister
	ReqBand
	RespBand
	ReqCheckAccount
	RespCheckAccount
	ReqScheduling
	RespScheduling
	ReqFindJob
	RespFindJob
	ReqPay
	RespPay
	ReqSetContent
	RespSetContent
	ReqGetContent
	RespGetContent
	ReqGetCanApply
	RespGetCanApply
	ReqGetSchedue
	RespGetSchedue
	ReqGetBalance
	RespGetBalance
	ReqCheckIsOkApplication
	RespCheckIsOkApplication
	ReqManageContract
	RespManageContract
	ReqCheckContract
	RespCheckContract
	ReqGetStaff
	RespGetStaff
	ReqLogin
	RespLogin
	ReqGetAllOrder
	RespGetAllOrder
	ReqGetAllMoney
	RespGetAllMoney
	ReqHistoryJoin
	RespHistoryJoin
	ReqGetAllIncome
	RespGetAllIncome
	ReqGetIncomeBySchedule
	RespGetIncomeBySchedule
	CReloadConfig
	SReloadConfig
	CReloadDeploy
	SReloadDeploy
	ReqGetConfig
	RespGetConfig
	ReqSetConfig
	RespSetConfig
	Job
	Unit
	Schedule
	ScheduleStaff
	Order
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 测试用
type Req struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 测试用
type Resp struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 客户端 获取以太坊的余额
type ReqGetEthBalance struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
}

func (m *ReqGetEthBalance) Reset()                    { *m = ReqGetEthBalance{} }
func (m *ReqGetEthBalance) String() string            { return proto.CompactTextString(m) }
func (*ReqGetEthBalance) ProtoMessage()               {}
func (*ReqGetEthBalance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReqGetEthBalance) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

// 服务端 获取以太坊的余额
type RespGetEthBalance struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Balance    string `protobuf:"bytes,2,opt,name=Balance" json:"Balance,omitempty"`
}

func (m *RespGetEthBalance) Reset()                    { *m = RespGetEthBalance{} }
func (m *RespGetEthBalance) String() string            { return proto.CompactTextString(m) }
func (*RespGetEthBalance) ProtoMessage()               {}
func (*RespGetEthBalance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RespGetEthBalance) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetEthBalance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

// 客户端 注册
type ReqRegister struct {
	PassWord string `protobuf:"bytes,1,opt,name=PassWord" json:"PassWord,omitempty"`
}

func (m *ReqRegister) Reset()                    { *m = ReqRegister{} }
func (m *ReqRegister) String() string            { return proto.CompactTextString(m) }
func (*ReqRegister) ProtoMessage()               {}
func (*ReqRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReqRegister) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

// 服务端 注册
type RespRegister struct {
	StatusCode      uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	UserAddress     string `protobuf:"bytes,2,opt,name=UserAddress" json:"UserAddress,omitempty"`
	PassWord        string `protobuf:"bytes,3,opt,name=PassWord" json:"PassWord,omitempty"`
	AccountDescribe string `protobuf:"bytes,4,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
}

func (m *RespRegister) Reset()                    { *m = RespRegister{} }
func (m *RespRegister) String() string            { return proto.CompactTextString(m) }
func (*RespRegister) ProtoMessage()               {}
func (*RespRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RespRegister) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespRegister) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *RespRegister) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *RespRegister) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

// 客户端 绑定
type ReqBand struct {
	Name            string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	UserAddress     string `protobuf:"bytes,2,opt,name=UserAddress" json:"UserAddress,omitempty"`
	Role            string `protobuf:"bytes,3,opt,name=Role" json:"Role,omitempty"`
	PassWord        string `protobuf:"bytes,4,opt,name=PassWord" json:"PassWord,omitempty"`
	Phone           string `protobuf:"bytes,5,opt,name=Phone" json:"Phone,omitempty"`
	AccountDescribe string `protobuf:"bytes,6,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
}

func (m *ReqBand) Reset()                    { *m = ReqBand{} }
func (m *ReqBand) String() string            { return proto.CompactTextString(m) }
func (*ReqBand) ProtoMessage()               {}
func (*ReqBand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReqBand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqBand) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqBand) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ReqBand) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *ReqBand) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ReqBand) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

// 服务端 绑定
type RespBand struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
}

func (m *RespBand) Reset()                    { *m = RespBand{} }
func (m *RespBand) String() string            { return proto.CompactTextString(m) }
func (*RespBand) ProtoMessage()               {}
func (*RespBand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RespBand) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

// 客户端 查询账户
type ReqCheckAccount struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
}

func (m *ReqCheckAccount) Reset()                    { *m = ReqCheckAccount{} }
func (m *ReqCheckAccount) String() string            { return proto.CompactTextString(m) }
func (*ReqCheckAccount) ProtoMessage()               {}
func (*ReqCheckAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReqCheckAccount) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

// 服务端 查询账户
type RespCheckAccount struct {
	StatusCode      uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Role            string `protobuf:"bytes,3,opt,name=Role" json:"Role,omitempty"`
	PassWord        string `protobuf:"bytes,4,opt,name=PassWord" json:"PassWord,omitempty"`
	Phone           string `protobuf:"bytes,5,opt,name=Phone" json:"Phone,omitempty"`
	AccountDescribe string `protobuf:"bytes,6,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
}

func (m *RespCheckAccount) Reset()                    { *m = RespCheckAccount{} }
func (m *RespCheckAccount) String() string            { return proto.CompactTextString(m) }
func (*RespCheckAccount) ProtoMessage()               {}
func (*RespCheckAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RespCheckAccount) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespCheckAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RespCheckAccount) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RespCheckAccount) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *RespCheckAccount) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RespCheckAccount) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

// 客户端 发布排班
type ReqScheduling struct {
	UserAddress     string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	PassWord        string `protobuf:"bytes,2,opt,name=PassWord" json:"PassWord,omitempty"`
	AccountDescribe string `protobuf:"bytes,3,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
	Company         string `protobuf:"bytes,4,opt,name=Company" json:"Company,omitempty"`
	Jobs            []*Job `protobuf:"bytes,5,rep,name=Jobs" json:"Jobs,omitempty"`
	TimeStamp       int64  `protobuf:"varint,6,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *ReqScheduling) Reset()                    { *m = ReqScheduling{} }
func (m *ReqScheduling) String() string            { return proto.CompactTextString(m) }
func (*ReqScheduling) ProtoMessage()               {}
func (*ReqScheduling) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ReqScheduling) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqScheduling) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *ReqScheduling) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

func (m *ReqScheduling) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *ReqScheduling) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *ReqScheduling) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

// 服务端 发布排班
type RespScheduling struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	JobAddress string `protobuf:"bytes,2,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *RespScheduling) Reset()                    { *m = RespScheduling{} }
func (m *RespScheduling) String() string            { return proto.CompactTextString(m) }
func (*RespScheduling) ProtoMessage()               {}
func (*RespScheduling) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RespScheduling) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespScheduling) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

// 客户端 申请工作
type ReqFindJob struct {
	UserAddress     string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	PassWord        string `protobuf:"bytes,2,opt,name=PassWord" json:"PassWord,omitempty"`
	AccountDescribe string `protobuf:"bytes,3,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
	MyJob           *Job   `protobuf:"bytes,4,opt,name=MyJob" json:"MyJob,omitempty"`
}

func (m *ReqFindJob) Reset()                    { *m = ReqFindJob{} }
func (m *ReqFindJob) String() string            { return proto.CompactTextString(m) }
func (*ReqFindJob) ProtoMessage()               {}
func (*ReqFindJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ReqFindJob) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqFindJob) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *ReqFindJob) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

func (m *ReqFindJob) GetMyJob() *Job {
	if m != nil {
		return m.MyJob
	}
	return nil
}

// 服务端 申请工作
type RespFindJob struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	HashCode   string `protobuf:"bytes,2,opt,name=HashCode" json:"HashCode,omitempty"`
}

func (m *RespFindJob) Reset()                    { *m = RespFindJob{} }
func (m *RespFindJob) String() string            { return proto.CompactTextString(m) }
func (*RespFindJob) ProtoMessage()               {}
func (*RespFindJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RespFindJob) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespFindJob) GetHashCode() string {
	if m != nil {
		return m.HashCode
	}
	return ""
}

// 客户端 确认存证并付款
type ReqPay struct {
	UserAddress     string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	PassWord        string `protobuf:"bytes,2,opt,name=PassWord" json:"PassWord,omitempty"`
	AccountDescribe string `protobuf:"bytes,3,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
	Money           uint64 `protobuf:"varint,4,opt,name=Money" json:"Money,omitempty"`
	Content         *Order `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	JobAddress      string `protobuf:"bytes,6,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *ReqPay) Reset()                    { *m = ReqPay{} }
func (m *ReqPay) String() string            { return proto.CompactTextString(m) }
func (*ReqPay) ProtoMessage()               {}
func (*ReqPay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ReqPay) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqPay) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *ReqPay) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

func (m *ReqPay) GetMoney() uint64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *ReqPay) GetContent() *Order {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ReqPay) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

// 服务端 确认存证并付款
type RespPay struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	OrderId    uint32 `protobuf:"varint,2,opt,name=OrderId" json:"OrderId,omitempty"`
	HashCode   string `protobuf:"bytes,3,opt,name=HashCode" json:"HashCode,omitempty"`
}

func (m *RespPay) Reset()                    { *m = RespPay{} }
func (m *RespPay) String() string            { return proto.CompactTextString(m) }
func (*RespPay) ProtoMessage()               {}
func (*RespPay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RespPay) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespPay) GetOrderId() uint32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *RespPay) GetHashCode() string {
	if m != nil {
		return m.HashCode
	}
	return ""
}

// 客户端 客户下单
type ReqSetContent struct {
	UserAddress     string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	PassWord        string `protobuf:"bytes,2,opt,name=PassWord" json:"PassWord,omitempty"`
	AccountDescribe string `protobuf:"bytes,3,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
	OrderId         string `protobuf:"bytes,4,opt,name=OrderId" json:"OrderId,omitempty"`
	Content         *Order `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	JobAddress      string `protobuf:"bytes,6,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *ReqSetContent) Reset()                    { *m = ReqSetContent{} }
func (m *ReqSetContent) String() string            { return proto.CompactTextString(m) }
func (*ReqSetContent) ProtoMessage()               {}
func (*ReqSetContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ReqSetContent) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqSetContent) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *ReqSetContent) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

func (m *ReqSetContent) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ReqSetContent) GetContent() *Order {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ReqSetContent) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

// 服务端 客户下单
type RespSetContent struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	OrderId    string `protobuf:"bytes,2,opt,name=OrderId" json:"OrderId,omitempty"`
}

func (m *RespSetContent) Reset()                    { *m = RespSetContent{} }
func (m *RespSetContent) String() string            { return proto.CompactTextString(m) }
func (*RespSetContent) ProtoMessage()               {}
func (*RespSetContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RespSetContent) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespSetContent) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

// 客户端 客户查单
type ReqGetContent struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	OrderId     string `protobuf:"bytes,2,opt,name=OrderId" json:"OrderId,omitempty"`
	JobAddress  string `protobuf:"bytes,3,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *ReqGetContent) Reset()                    { *m = ReqGetContent{} }
func (m *ReqGetContent) String() string            { return proto.CompactTextString(m) }
func (*ReqGetContent) ProtoMessage()               {}
func (*ReqGetContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ReqGetContent) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetContent) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ReqGetContent) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

// 服务端 客户查单
type RespGetContent struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Content    *Order `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *RespGetContent) Reset()                    { *m = RespGetContent{} }
func (m *RespGetContent) String() string            { return proto.CompactTextString(m) }
func (*RespGetContent) ProtoMessage()               {}
func (*RespGetContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RespGetContent) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetContent) GetContent() *Order {
	if m != nil {
		return m.Content
	}
	return nil
}

// 服务端 查询可申请的工作
type ReqGetCanApply struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=CompanyName" json:"CompanyName,omitempty"`
	TimeStamp   string `protobuf:"bytes,3,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *ReqGetCanApply) Reset()                    { *m = ReqGetCanApply{} }
func (m *ReqGetCanApply) String() string            { return proto.CompactTextString(m) }
func (*ReqGetCanApply) ProtoMessage()               {}
func (*ReqGetCanApply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ReqGetCanApply) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetCanApply) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ReqGetCanApply) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

// 客户端 查询可申请的工作
type RespGetCanApply struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Jobs       []*Job `protobuf:"bytes,2,rep,name=Jobs" json:"Jobs,omitempty"`
}

func (m *RespGetCanApply) Reset()                    { *m = RespGetCanApply{} }
func (m *RespGetCanApply) String() string            { return proto.CompactTextString(m) }
func (*RespGetCanApply) ProtoMessage()               {}
func (*RespGetCanApply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RespGetCanApply) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetCanApply) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// 客户端 查询排班
type ReqGetSchedue struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=CompanyName" json:"CompanyName,omitempty"`
	TimeStamp   string `protobuf:"bytes,3,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *ReqGetSchedue) Reset()                    { *m = ReqGetSchedue{} }
func (m *ReqGetSchedue) String() string            { return proto.CompactTextString(m) }
func (*ReqGetSchedue) ProtoMessage()               {}
func (*ReqGetSchedue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ReqGetSchedue) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetSchedue) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ReqGetSchedue) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

// 服务端 查询排班
type RespGetSchedue struct {
	StatusCode uint32      `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Schedules  []*Schedule `protobuf:"bytes,2,rep,name=Schedules" json:"Schedules,omitempty"`
}

func (m *RespGetSchedue) Reset()                    { *m = RespGetSchedue{} }
func (m *RespGetSchedue) String() string            { return proto.CompactTextString(m) }
func (*RespGetSchedue) ProtoMessage()               {}
func (*RespGetSchedue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RespGetSchedue) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetSchedue) GetSchedules() []*Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

// 请求查询某一排班的收入
type ReqGetBalance struct {
	UserAddress    string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	SchedueAddress string `protobuf:"bytes,2,opt,name=SchedueAddress" json:"SchedueAddress,omitempty"`
}

func (m *ReqGetBalance) Reset()                    { *m = ReqGetBalance{} }
func (m *ReqGetBalance) String() string            { return proto.CompactTextString(m) }
func (*ReqGetBalance) ProtoMessage()               {}
func (*ReqGetBalance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ReqGetBalance) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetBalance) GetSchedueAddress() string {
	if m != nil {
		return m.SchedueAddress
	}
	return ""
}

// 请求查询某一排班的收入
type RespGetBalance struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Money      uint64 `protobuf:"varint,2,opt,name=Money" json:"Money,omitempty"`
}

func (m *RespGetBalance) Reset()                    { *m = RespGetBalance{} }
func (m *RespGetBalance) String() string            { return proto.CompactTextString(m) }
func (*RespGetBalance) ProtoMessage()               {}
func (*RespGetBalance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *RespGetBalance) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetBalance) GetMoney() uint64 {
	if m != nil {
		return m.Money
	}
	return 0
}

// ----请求查询工作是否申请成功
type ReqCheckIsOkApplication struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	JobAddress  string `protobuf:"bytes,2,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *ReqCheckIsOkApplication) Reset()                    { *m = ReqCheckIsOkApplication{} }
func (m *ReqCheckIsOkApplication) String() string            { return proto.CompactTextString(m) }
func (*ReqCheckIsOkApplication) ProtoMessage()               {}
func (*ReqCheckIsOkApplication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ReqCheckIsOkApplication) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqCheckIsOkApplication) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

type RespCheckIsOkApplication struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	IsApplied  bool   `protobuf:"varint,2,opt,name=isApplied" json:"isApplied,omitempty"`
}

func (m *RespCheckIsOkApplication) Reset()                    { *m = RespCheckIsOkApplication{} }
func (m *RespCheckIsOkApplication) String() string            { return proto.CompactTextString(m) }
func (*RespCheckIsOkApplication) ProtoMessage()               {}
func (*RespCheckIsOkApplication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *RespCheckIsOkApplication) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespCheckIsOkApplication) GetIsApplied() bool {
	if m != nil {
		return m.IsApplied
	}
	return false
}

// 客户端 管理合约(占时没用)
type ReqManageContract struct {
	UserAddress  string   `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	ContractHash uint64   `protobuf:"varint,2,opt,name=ContractHash" json:"ContractHash,omitempty"`
	Pre          []string `protobuf:"bytes,3,rep,name=Pre" json:"Pre,omitempty"`
	After        []string `protobuf:"bytes,4,rep,name=After" json:"After,omitempty"`
}

func (m *ReqManageContract) Reset()                    { *m = ReqManageContract{} }
func (m *ReqManageContract) String() string            { return proto.CompactTextString(m) }
func (*ReqManageContract) ProtoMessage()               {}
func (*ReqManageContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ReqManageContract) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqManageContract) GetContractHash() uint64 {
	if m != nil {
		return m.ContractHash
	}
	return 0
}

func (m *ReqManageContract) GetPre() []string {
	if m != nil {
		return m.Pre
	}
	return nil
}

func (m *ReqManageContract) GetAfter() []string {
	if m != nil {
		return m.After
	}
	return nil
}

// 服务端 管理合约(占时没用)
type RespManageContract struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	HashCode   string `protobuf:"bytes,2,opt,name=HashCode" json:"HashCode,omitempty"`
}

func (m *RespManageContract) Reset()                    { *m = RespManageContract{} }
func (m *RespManageContract) String() string            { return proto.CompactTextString(m) }
func (*RespManageContract) ProtoMessage()               {}
func (*RespManageContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *RespManageContract) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespManageContract) GetHashCode() string {
	if m != nil {
		return m.HashCode
	}
	return ""
}

// 客户端 查询合约
type ReqCheckContract struct {
	Address string `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
}

func (m *ReqCheckContract) Reset()                    { *m = ReqCheckContract{} }
func (m *ReqCheckContract) String() string            { return proto.CompactTextString(m) }
func (*ReqCheckContract) ProtoMessage()               {}
func (*ReqCheckContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ReqCheckContract) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqCheckContract) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// 服务端 查询合约
type RespCheckContract struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	HashCode   string `protobuf:"bytes,2,opt,name=HashCode" json:"HashCode,omitempty"`
}

func (m *RespCheckContract) Reset()                    { *m = RespCheckContract{} }
func (m *RespCheckContract) String() string            { return proto.CompactTextString(m) }
func (*RespCheckContract) ProtoMessage()               {}
func (*RespCheckContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *RespCheckContract) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespCheckContract) GetHashCode() string {
	if m != nil {
		return m.HashCode
	}
	return ""
}

// 客户端 查询合约
type ReqGetStaff struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	JobAddress  string `protobuf:"bytes,2,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *ReqGetStaff) Reset()                    { *m = ReqGetStaff{} }
func (m *ReqGetStaff) String() string            { return proto.CompactTextString(m) }
func (*ReqGetStaff) ProtoMessage()               {}
func (*ReqGetStaff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ReqGetStaff) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetStaff) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

// 服务端 查询合约
type RespGetStaff struct {
	StatusCode uint32           `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Staffs     []*ScheduleStaff `protobuf:"bytes,2,rep,name=Staffs" json:"Staffs,omitempty"`
}

func (m *RespGetStaff) Reset()                    { *m = RespGetStaff{} }
func (m *RespGetStaff) String() string            { return proto.CompactTextString(m) }
func (*RespGetStaff) ProtoMessage()               {}
func (*RespGetStaff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *RespGetStaff) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetStaff) GetStaffs() []*ScheduleStaff {
	if m != nil {
		return m.Staffs
	}
	return nil
}

// 客户端 登录服务
type ReqLogin struct {
	Phone string `protobuf:"bytes,1,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *ReqLogin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// 服务端 登录服务
type RespLogin struct {
	StatusCode      uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Role            string `protobuf:"bytes,3,opt,name=Role" json:"Role,omitempty"`
	PassWord        string `protobuf:"bytes,4,opt,name=PassWord" json:"PassWord,omitempty"`
	Phone           string `protobuf:"bytes,5,opt,name=Phone" json:"Phone,omitempty"`
	Address         string `protobuf:"bytes,6,opt,name=Address" json:"Address,omitempty"`
	AccountDescribe string `protobuf:"bytes,7,opt,name=AccountDescribe" json:"AccountDescribe,omitempty"`
}

func (m *RespLogin) Reset()                    { *m = RespLogin{} }
func (m *RespLogin) String() string            { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()               {}
func (*RespLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *RespLogin) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RespLogin) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RespLogin) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *RespLogin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RespLogin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RespLogin) GetAccountDescribe() string {
	if m != nil {
		return m.AccountDescribe
	}
	return ""
}

// 客户端 查詢排班下所有訂單
type ReqGetAllOrder struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	JobAddress  string `protobuf:"bytes,2,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *ReqGetAllOrder) Reset()                    { *m = ReqGetAllOrder{} }
func (m *ReqGetAllOrder) String() string            { return proto.CompactTextString(m) }
func (*ReqGetAllOrder) ProtoMessage()               {}
func (*ReqGetAllOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *ReqGetAllOrder) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetAllOrder) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

// 服务端 查詢排班下所有訂單
type RespGetAllOrder struct {
	StatusCode uint32   `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Orders     []*Order `protobuf:"bytes,2,rep,name=Orders" json:"Orders,omitempty"`
	Sum        float64  `protobuf:"fixed64,3,opt,name=Sum" json:"Sum,omitempty"`
}

func (m *RespGetAllOrder) Reset()                    { *m = RespGetAllOrder{} }
func (m *RespGetAllOrder) String() string            { return proto.CompactTextString(m) }
func (*RespGetAllOrder) ProtoMessage()               {}
func (*RespGetAllOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *RespGetAllOrder) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetAllOrder) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *RespGetAllOrder) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

// 客户端 查询用户在某一公司所有收入
type ReqGetAllMoney struct {
	CompanyName string `protobuf:"bytes,1,opt,name=CompanyName" json:"CompanyName,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=UserAddress" json:"UserAddress,omitempty"`
}

func (m *ReqGetAllMoney) Reset()                    { *m = ReqGetAllMoney{} }
func (m *ReqGetAllMoney) String() string            { return proto.CompactTextString(m) }
func (*ReqGetAllMoney) ProtoMessage()               {}
func (*ReqGetAllMoney) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *ReqGetAllMoney) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ReqGetAllMoney) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

// 服务端 查詢排班下所有訂單
type RespGetAllMoney struct {
	StatusCode uint32  `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Sum        float64 `protobuf:"fixed64,2,opt,name=Sum" json:"Sum,omitempty"`
}

func (m *RespGetAllMoney) Reset()                    { *m = RespGetAllMoney{} }
func (m *RespGetAllMoney) String() string            { return proto.CompactTextString(m) }
func (*RespGetAllMoney) ProtoMessage()               {}
func (*RespGetAllMoney) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *RespGetAllMoney) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetAllMoney) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

// 客户端 用户申请工作历史
type ReqHistoryJoin struct {
	UserAddress string `protobuf:"bytes,1,opt,name=UserAddress" json:"UserAddress,omitempty"`
	Company     string `protobuf:"bytes,2,opt,name=Company" json:"Company,omitempty"`
}

func (m *ReqHistoryJoin) Reset()                    { *m = ReqHistoryJoin{} }
func (m *ReqHistoryJoin) String() string            { return proto.CompactTextString(m) }
func (*ReqHistoryJoin) ProtoMessage()               {}
func (*ReqHistoryJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *ReqHistoryJoin) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqHistoryJoin) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

// 服务端 用户申请工作历史
type RespHistoryJoin struct {
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Jobs       []*Job `protobuf:"bytes,2,rep,name=Jobs" json:"Jobs,omitempty"`
}

func (m *RespHistoryJoin) Reset()                    { *m = RespHistoryJoin{} }
func (m *RespHistoryJoin) String() string            { return proto.CompactTextString(m) }
func (*RespHistoryJoin) ProtoMessage()               {}
func (*RespHistoryJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *RespHistoryJoin) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespHistoryJoin) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// 客户端 获取用户收入明细
type ReqGetAllIncome struct {
	CompanyName string `protobuf:"bytes,1,opt,name=CompanyName" json:"CompanyName,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=UserAddress" json:"UserAddress,omitempty"`
}

func (m *ReqGetAllIncome) Reset()                    { *m = ReqGetAllIncome{} }
func (m *ReqGetAllIncome) String() string            { return proto.CompactTextString(m) }
func (*ReqGetAllIncome) ProtoMessage()               {}
func (*ReqGetAllIncome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *ReqGetAllIncome) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ReqGetAllIncome) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

// 服务端 获取用户收入明细
type RespGetAllIncome struct {
	StatusCode uint32   `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Orders     []*Order `protobuf:"bytes,2,rep,name=Orders" json:"Orders,omitempty"`
}

func (m *RespGetAllIncome) Reset()                    { *m = RespGetAllIncome{} }
func (m *RespGetAllIncome) String() string            { return proto.CompactTextString(m) }
func (*RespGetAllIncome) ProtoMessage()               {}
func (*RespGetAllIncome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *RespGetAllIncome) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetAllIncome) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// 客户端 根据排班信息获取玩家收入详情
type ReqGetIncomeBySchedule struct {
	CompanyName string `protobuf:"bytes,1,opt,name=CompanyName" json:"CompanyName,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=UserAddress" json:"UserAddress,omitempty"`
	TimeStamp   string `protobuf:"bytes,3,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *ReqGetIncomeBySchedule) Reset()                    { *m = ReqGetIncomeBySchedule{} }
func (m *ReqGetIncomeBySchedule) String() string            { return proto.CompactTextString(m) }
func (*ReqGetIncomeBySchedule) ProtoMessage()               {}
func (*ReqGetIncomeBySchedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *ReqGetIncomeBySchedule) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ReqGetIncomeBySchedule) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *ReqGetIncomeBySchedule) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

// 服务端 根据排班信息获取玩家收入详情
type RespGetIncomeBySchedule struct {
	StatusCode uint32   `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	Orders     []*Order `protobuf:"bytes,2,rep,name=Orders" json:"Orders,omitempty"`
}

func (m *RespGetIncomeBySchedule) Reset()                    { *m = RespGetIncomeBySchedule{} }
func (m *RespGetIncomeBySchedule) String() string            { return proto.CompactTextString(m) }
func (*RespGetIncomeBySchedule) ProtoMessage()               {}
func (*RespGetIncomeBySchedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *RespGetIncomeBySchedule) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespGetIncomeBySchedule) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type CReloadConfig struct {
	OperateTimeout uint32 `protobuf:"varint,1,opt,name=Operate_timeout,json=OperateTimeout" json:"Operate_timeout,omitempty"`
	LocalAddress   string `protobuf:"bytes,2,opt,name=LocalAddress" json:"LocalAddress,omitempty"`
	Port           string `protobuf:"bytes,3,opt,name=Port" json:"Port,omitempty"`
	AccAddress     string `protobuf:"bytes,4,opt,name=AccAddress" json:"AccAddress,omitempty"`
	EthAddress     string `protobuf:"bytes,5,opt,name=EthAddress" json:"EthAddress,omitempty"`
	IpcDir         string `protobuf:"bytes,6,opt,name=IpcDir" json:"IpcDir,omitempty"`
	ServerId       string `protobuf:"bytes,7,opt,name=ServerId" json:"ServerId,omitempty"`
	ManagerKey     string `protobuf:"bytes,8,opt,name=ManagerKey" json:"ManagerKey,omitempty"`
	ManagerPhrase  string `protobuf:"bytes,9,opt,name=ManagerPhrase" json:"ManagerPhrase,omitempty"`
	KeyDir         string `protobuf:"bytes,10,opt,name=KeyDir" json:"KeyDir,omitempty"`
}

func (m *CReloadConfig) Reset()                    { *m = CReloadConfig{} }
func (m *CReloadConfig) String() string            { return proto.CompactTextString(m) }
func (*CReloadConfig) ProtoMessage()               {}
func (*CReloadConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *CReloadConfig) GetOperateTimeout() uint32 {
	if m != nil {
		return m.OperateTimeout
	}
	return 0
}

func (m *CReloadConfig) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *CReloadConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CReloadConfig) GetAccAddress() string {
	if m != nil {
		return m.AccAddress
	}
	return ""
}

func (m *CReloadConfig) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *CReloadConfig) GetIpcDir() string {
	if m != nil {
		return m.IpcDir
	}
	return ""
}

func (m *CReloadConfig) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *CReloadConfig) GetManagerKey() string {
	if m != nil {
		return m.ManagerKey
	}
	return ""
}

func (m *CReloadConfig) GetManagerPhrase() string {
	if m != nil {
		return m.ManagerPhrase
	}
	return ""
}

func (m *CReloadConfig) GetKeyDir() string {
	if m != nil {
		return m.KeyDir
	}
	return ""
}

type SReloadConfig struct {
}

func (m *SReloadConfig) Reset()                    { *m = SReloadConfig{} }
func (m *SReloadConfig) String() string            { return proto.CompactTextString(m) }
func (*SReloadConfig) ProtoMessage()               {}
func (*SReloadConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

type CReloadDeploy struct {
	Address string `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
}

func (m *CReloadDeploy) Reset()                    { *m = CReloadDeploy{} }
func (m *CReloadDeploy) String() string            { return proto.CompactTextString(m) }
func (*CReloadDeploy) ProtoMessage()               {}
func (*CReloadDeploy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *CReloadDeploy) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CReloadDeploy) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type SReloadDeploy struct {
}

func (m *SReloadDeploy) Reset()                    { *m = SReloadDeploy{} }
func (m *SReloadDeploy) String() string            { return proto.CompactTextString(m) }
func (*SReloadDeploy) ProtoMessage()               {}
func (*SReloadDeploy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func init() {
	proto.RegisterType((*Req)(nil), "protocol.Req")
	proto.RegisterType((*Resp)(nil), "protocol.Resp")
	proto.RegisterType((*ReqGetEthBalance)(nil), "protocol.ReqGetEthBalance")
	proto.RegisterType((*RespGetEthBalance)(nil), "protocol.RespGetEthBalance")
	proto.RegisterType((*ReqRegister)(nil), "protocol.ReqRegister")
	proto.RegisterType((*RespRegister)(nil), "protocol.RespRegister")
	proto.RegisterType((*ReqBand)(nil), "protocol.ReqBand")
	proto.RegisterType((*RespBand)(nil), "protocol.RespBand")
	proto.RegisterType((*ReqCheckAccount)(nil), "protocol.ReqCheckAccount")
	proto.RegisterType((*RespCheckAccount)(nil), "protocol.RespCheckAccount")
	proto.RegisterType((*ReqScheduling)(nil), "protocol.ReqScheduling")
	proto.RegisterType((*RespScheduling)(nil), "protocol.RespScheduling")
	proto.RegisterType((*ReqFindJob)(nil), "protocol.ReqFindJob")
	proto.RegisterType((*RespFindJob)(nil), "protocol.RespFindJob")
	proto.RegisterType((*ReqPay)(nil), "protocol.ReqPay")
	proto.RegisterType((*RespPay)(nil), "protocol.RespPay")
	proto.RegisterType((*ReqSetContent)(nil), "protocol.ReqSetContent")
	proto.RegisterType((*RespSetContent)(nil), "protocol.RespSetContent")
	proto.RegisterType((*ReqGetContent)(nil), "protocol.ReqGetContent")
	proto.RegisterType((*RespGetContent)(nil), "protocol.RespGetContent")
	proto.RegisterType((*ReqGetCanApply)(nil), "protocol.ReqGetCanApply")
	proto.RegisterType((*RespGetCanApply)(nil), "protocol.RespGetCanApply")
	proto.RegisterType((*ReqGetSchedue)(nil), "protocol.ReqGetSchedue")
	proto.RegisterType((*RespGetSchedue)(nil), "protocol.RespGetSchedue")
	proto.RegisterType((*ReqGetBalance)(nil), "protocol.ReqGetBalance")
	proto.RegisterType((*RespGetBalance)(nil), "protocol.RespGetBalance")
	proto.RegisterType((*ReqCheckIsOkApplication)(nil), "protocol.ReqCheckIsOkApplication")
	proto.RegisterType((*RespCheckIsOkApplication)(nil), "protocol.RespCheckIsOkApplication")
	proto.RegisterType((*ReqManageContract)(nil), "protocol.ReqManageContract")
	proto.RegisterType((*RespManageContract)(nil), "protocol.RespManageContract")
	proto.RegisterType((*ReqCheckContract)(nil), "protocol.ReqCheckContract")
	proto.RegisterType((*RespCheckContract)(nil), "protocol.RespCheckContract")
	proto.RegisterType((*ReqGetStaff)(nil), "protocol.ReqGetStaff")
	proto.RegisterType((*RespGetStaff)(nil), "protocol.RespGetStaff")
	proto.RegisterType((*ReqLogin)(nil), "protocol.ReqLogin")
	proto.RegisterType((*RespLogin)(nil), "protocol.RespLogin")
	proto.RegisterType((*ReqGetAllOrder)(nil), "protocol.ReqGetAllOrder")
	proto.RegisterType((*RespGetAllOrder)(nil), "protocol.RespGetAllOrder")
	proto.RegisterType((*ReqGetAllMoney)(nil), "protocol.ReqGetAllMoney")
	proto.RegisterType((*RespGetAllMoney)(nil), "protocol.RespGetAllMoney")
	proto.RegisterType((*ReqHistoryJoin)(nil), "protocol.ReqHistoryJoin")
	proto.RegisterType((*RespHistoryJoin)(nil), "protocol.RespHistoryJoin")
	proto.RegisterType((*ReqGetAllIncome)(nil), "protocol.ReqGetAllIncome")
	proto.RegisterType((*RespGetAllIncome)(nil), "protocol.RespGetAllIncome")
	proto.RegisterType((*ReqGetIncomeBySchedule)(nil), "protocol.ReqGetIncomeBySchedule")
	proto.RegisterType((*RespGetIncomeBySchedule)(nil), "protocol.RespGetIncomeBySchedule")
	proto.RegisterType((*CReloadConfig)(nil), "protocol.CReloadConfig")
	proto.RegisterType((*SReloadConfig)(nil), "protocol.SReloadConfig")
	proto.RegisterType((*CReloadDeploy)(nil), "protocol.CReloadDeploy")
	proto.RegisterType((*SReloadDeploy)(nil), "protocol.SReloadDeploy")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiService service

type ApiServiceClient interface {
	SayHello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	// 注册 绑定 登录
	Register(ctx context.Context, in *ReqRegister, opts ...grpc.CallOption) (*RespRegister, error)
	Band(ctx context.Context, in *ReqBand, opts ...grpc.CallOption) (*RespBand, error)
	Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*RespLogin, error)
	CheckAccount(ctx context.Context, in *ReqCheckAccount, opts ...grpc.CallOption) (*RespCheckAccount, error)
	GetEthBalance(ctx context.Context, in *ReqGetEthBalance, opts ...grpc.CallOption) (*RespGetEthBalance, error)
	// 排班 申请工作
	SetSchedule(ctx context.Context, in *ReqScheduling, opts ...grpc.CallOption) (*RespScheduling, error)
	GetSchedule(ctx context.Context, in *ReqGetSchedue, opts ...grpc.CallOption) (*RespGetSchedue, error)
	GetCanJoin(ctx context.Context, in *ReqGetSchedue, opts ...grpc.CallOption) (*RespGetSchedue, error)
	GetApply(ctx context.Context, in *ReqGetStaff, opts ...grpc.CallOption) (*RespGetStaff, error)
	GetJob(ctx context.Context, in *ReqGetCanApply, opts ...grpc.CallOption) (*RespGetCanApply, error)
	ApplyJob(ctx context.Context, in *ReqFindJob, opts ...grpc.CallOption) (*RespFindJob, error)
	HistoryJoin(ctx context.Context, in *ReqHistoryJoin, opts ...grpc.CallOption) (*RespHistoryJoin, error)
	CheckIsOkApplication(ctx context.Context, in *ReqCheckIsOkApplication, opts ...grpc.CallOption) (*RespCheckIsOkApplication, error)
	// 收入
	Pay(ctx context.Context, in *ReqPay, opts ...grpc.CallOption) (*RespPay, error)
	GetAllOrderBySchedule(ctx context.Context, in *ReqGetAllOrder, opts ...grpc.CallOption) (*RespGetAllOrder, error)
	GetContent(ctx context.Context, in *ReqGetContent, opts ...grpc.CallOption) (*RespGetContent, error)
	GetAllIncome(ctx context.Context, in *ReqGetAllIncome, opts ...grpc.CallOption) (*RespGetAllIncome, error)
	GetIncomeBySchedule(ctx context.Context, in *ReqGetIncomeBySchedule, opts ...grpc.CallOption) (*RespGetIncomeBySchedule, error)
	// 查询
	GetBalance(ctx context.Context, in *ReqGetBalance, opts ...grpc.CallOption) (*RespGetBalance, error)
	GetAllMoney(ctx context.Context, in *ReqGetAllMoney, opts ...grpc.CallOption) (*RespGetAllMoney, error)
	// 无用
	ManageContract(ctx context.Context, in *ReqManageContract, opts ...grpc.CallOption) (*RespManageContract, error)
	CheckContract(ctx context.Context, in *ReqCheckContract, opts ...grpc.CallOption) (*RespCheckContract, error)
	// 配置服务
	ReloadConfig(ctx context.Context, in *CReloadConfig, opts ...grpc.CallOption) (*SReloadConfig, error)
	ReloadDeploy(ctx context.Context, in *CReloadDeploy, opts ...grpc.CallOption) (*SReloadDeploy, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) SayHello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := grpc.Invoke(ctx, "/protocol.ApiService/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) Register(ctx context.Context, in *ReqRegister, opts ...grpc.CallOption) (*RespRegister, error) {
	out := new(RespRegister)
	err := grpc.Invoke(ctx, "/protocol.ApiService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) Band(ctx context.Context, in *ReqBand, opts ...grpc.CallOption) (*RespBand, error) {
	out := new(RespBand)
	err := grpc.Invoke(ctx, "/protocol.ApiService/Band", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*RespLogin, error) {
	out := new(RespLogin)
	err := grpc.Invoke(ctx, "/protocol.ApiService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) CheckAccount(ctx context.Context, in *ReqCheckAccount, opts ...grpc.CallOption) (*RespCheckAccount, error) {
	out := new(RespCheckAccount)
	err := grpc.Invoke(ctx, "/protocol.ApiService/CheckAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetEthBalance(ctx context.Context, in *ReqGetEthBalance, opts ...grpc.CallOption) (*RespGetEthBalance, error) {
	out := new(RespGetEthBalance)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetEthBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) SetSchedule(ctx context.Context, in *ReqScheduling, opts ...grpc.CallOption) (*RespScheduling, error) {
	out := new(RespScheduling)
	err := grpc.Invoke(ctx, "/protocol.ApiService/SetSchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetSchedule(ctx context.Context, in *ReqGetSchedue, opts ...grpc.CallOption) (*RespGetSchedue, error) {
	out := new(RespGetSchedue)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetSchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetCanJoin(ctx context.Context, in *ReqGetSchedue, opts ...grpc.CallOption) (*RespGetSchedue, error) {
	out := new(RespGetSchedue)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetCanJoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetApply(ctx context.Context, in *ReqGetStaff, opts ...grpc.CallOption) (*RespGetStaff, error) {
	out := new(RespGetStaff)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetApply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetJob(ctx context.Context, in *ReqGetCanApply, opts ...grpc.CallOption) (*RespGetCanApply, error) {
	out := new(RespGetCanApply)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ApplyJob(ctx context.Context, in *ReqFindJob, opts ...grpc.CallOption) (*RespFindJob, error) {
	out := new(RespFindJob)
	err := grpc.Invoke(ctx, "/protocol.ApiService/ApplyJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) HistoryJoin(ctx context.Context, in *ReqHistoryJoin, opts ...grpc.CallOption) (*RespHistoryJoin, error) {
	out := new(RespHistoryJoin)
	err := grpc.Invoke(ctx, "/protocol.ApiService/HistoryJoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) CheckIsOkApplication(ctx context.Context, in *ReqCheckIsOkApplication, opts ...grpc.CallOption) (*RespCheckIsOkApplication, error) {
	out := new(RespCheckIsOkApplication)
	err := grpc.Invoke(ctx, "/protocol.ApiService/CheckIsOkApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) Pay(ctx context.Context, in *ReqPay, opts ...grpc.CallOption) (*RespPay, error) {
	out := new(RespPay)
	err := grpc.Invoke(ctx, "/protocol.ApiService/Pay", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetAllOrderBySchedule(ctx context.Context, in *ReqGetAllOrder, opts ...grpc.CallOption) (*RespGetAllOrder, error) {
	out := new(RespGetAllOrder)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetAllOrderBySchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetContent(ctx context.Context, in *ReqGetContent, opts ...grpc.CallOption) (*RespGetContent, error) {
	out := new(RespGetContent)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetAllIncome(ctx context.Context, in *ReqGetAllIncome, opts ...grpc.CallOption) (*RespGetAllIncome, error) {
	out := new(RespGetAllIncome)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetAllIncome", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetIncomeBySchedule(ctx context.Context, in *ReqGetIncomeBySchedule, opts ...grpc.CallOption) (*RespGetIncomeBySchedule, error) {
	out := new(RespGetIncomeBySchedule)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetIncomeBySchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetBalance(ctx context.Context, in *ReqGetBalance, opts ...grpc.CallOption) (*RespGetBalance, error) {
	out := new(RespGetBalance)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetAllMoney(ctx context.Context, in *ReqGetAllMoney, opts ...grpc.CallOption) (*RespGetAllMoney, error) {
	out := new(RespGetAllMoney)
	err := grpc.Invoke(ctx, "/protocol.ApiService/GetAllMoney", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ManageContract(ctx context.Context, in *ReqManageContract, opts ...grpc.CallOption) (*RespManageContract, error) {
	out := new(RespManageContract)
	err := grpc.Invoke(ctx, "/protocol.ApiService/ManageContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) CheckContract(ctx context.Context, in *ReqCheckContract, opts ...grpc.CallOption) (*RespCheckContract, error) {
	out := new(RespCheckContract)
	err := grpc.Invoke(ctx, "/protocol.ApiService/CheckContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ReloadConfig(ctx context.Context, in *CReloadConfig, opts ...grpc.CallOption) (*SReloadConfig, error) {
	out := new(SReloadConfig)
	err := grpc.Invoke(ctx, "/protocol.ApiService/ReloadConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ReloadDeploy(ctx context.Context, in *CReloadDeploy, opts ...grpc.CallOption) (*SReloadDeploy, error) {
	out := new(SReloadDeploy)
	err := grpc.Invoke(ctx, "/protocol.ApiService/ReloadDeploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiService service

type ApiServiceServer interface {
	SayHello(context.Context, *Req) (*Resp, error)
	// 注册 绑定 登录
	Register(context.Context, *ReqRegister) (*RespRegister, error)
	Band(context.Context, *ReqBand) (*RespBand, error)
	Login(context.Context, *ReqLogin) (*RespLogin, error)
	CheckAccount(context.Context, *ReqCheckAccount) (*RespCheckAccount, error)
	GetEthBalance(context.Context, *ReqGetEthBalance) (*RespGetEthBalance, error)
	// 排班 申请工作
	SetSchedule(context.Context, *ReqScheduling) (*RespScheduling, error)
	GetSchedule(context.Context, *ReqGetSchedue) (*RespGetSchedue, error)
	GetCanJoin(context.Context, *ReqGetSchedue) (*RespGetSchedue, error)
	GetApply(context.Context, *ReqGetStaff) (*RespGetStaff, error)
	GetJob(context.Context, *ReqGetCanApply) (*RespGetCanApply, error)
	ApplyJob(context.Context, *ReqFindJob) (*RespFindJob, error)
	HistoryJoin(context.Context, *ReqHistoryJoin) (*RespHistoryJoin, error)
	CheckIsOkApplication(context.Context, *ReqCheckIsOkApplication) (*RespCheckIsOkApplication, error)
	// 收入
	Pay(context.Context, *ReqPay) (*RespPay, error)
	GetAllOrderBySchedule(context.Context, *ReqGetAllOrder) (*RespGetAllOrder, error)
	GetContent(context.Context, *ReqGetContent) (*RespGetContent, error)
	GetAllIncome(context.Context, *ReqGetAllIncome) (*RespGetAllIncome, error)
	GetIncomeBySchedule(context.Context, *ReqGetIncomeBySchedule) (*RespGetIncomeBySchedule, error)
	// 查询
	GetBalance(context.Context, *ReqGetBalance) (*RespGetBalance, error)
	GetAllMoney(context.Context, *ReqGetAllMoney) (*RespGetAllMoney, error)
	// 无用
	ManageContract(context.Context, *ReqManageContract) (*RespManageContract, error)
	CheckContract(context.Context, *ReqCheckContract) (*RespCheckContract, error)
	// 配置服务
	ReloadConfig(context.Context, *CReloadConfig) (*SReloadConfig, error)
	ReloadDeploy(context.Context, *CReloadDeploy) (*SReloadDeploy, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).SayHello(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Register(ctx, req.(*ReqRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_Band_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Band(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/Band",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Band(ctx, req.(*ReqBand))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Login(ctx, req.(*ReqLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCheckAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/CheckAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).CheckAccount(ctx, req.(*ReqCheckAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetEthBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetEthBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetEthBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetEthBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetEthBalance(ctx, req.(*ReqGetEthBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_SetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqScheduling)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).SetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/SetSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).SetSchedule(ctx, req.(*ReqScheduling))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetSchedue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetSchedule(ctx, req.(*ReqGetSchedue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetCanJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetSchedue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetCanJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetCanJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetCanJoin(ctx, req.(*ReqGetSchedue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetStaff)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetApply(ctx, req.(*ReqGetStaff))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetCanApply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetJob(ctx, req.(*ReqGetCanApply))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ApplyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqFindJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ApplyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/ApplyJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ApplyJob(ctx, req.(*ReqFindJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_HistoryJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqHistoryJoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).HistoryJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/HistoryJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).HistoryJoin(ctx, req.(*ReqHistoryJoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_CheckIsOkApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCheckIsOkApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).CheckIsOkApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/CheckIsOkApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).CheckIsOkApplication(ctx, req.(*ReqCheckIsOkApplication))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Pay(ctx, req.(*ReqPay))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetAllOrderBySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetAllOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAllOrderBySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetAllOrderBySchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAllOrderBySchedule(ctx, req.(*ReqGetAllOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetContent(ctx, req.(*ReqGetContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetAllIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetAllIncome)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAllIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetAllIncome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAllIncome(ctx, req.(*ReqGetAllIncome))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetIncomeBySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetIncomeBySchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetIncomeBySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetIncomeBySchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetIncomeBySchedule(ctx, req.(*ReqGetIncomeBySchedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetBalance(ctx, req.(*ReqGetBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetAllMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetAllMoney)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAllMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/GetAllMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAllMoney(ctx, req.(*ReqGetAllMoney))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ManageContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqManageContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ManageContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/ManageContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ManageContract(ctx, req.(*ReqManageContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_CheckContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCheckContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).CheckContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/CheckContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).CheckContract(ctx, req.(*ReqCheckContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CReloadConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ReloadConfig(ctx, req.(*CReloadConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ReloadDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CReloadDeploy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ReloadDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ApiService/ReloadDeploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ReloadDeploy(ctx, req.(*CReloadDeploy))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ApiService_SayHello_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ApiService_Register_Handler,
		},
		{
			MethodName: "Band",
			Handler:    _ApiService_Band_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ApiService_Login_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _ApiService_CheckAccount_Handler,
		},
		{
			MethodName: "GetEthBalance",
			Handler:    _ApiService_GetEthBalance_Handler,
		},
		{
			MethodName: "SetSchedule",
			Handler:    _ApiService_SetSchedule_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _ApiService_GetSchedule_Handler,
		},
		{
			MethodName: "GetCanJoin",
			Handler:    _ApiService_GetCanJoin_Handler,
		},
		{
			MethodName: "GetApply",
			Handler:    _ApiService_GetApply_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _ApiService_GetJob_Handler,
		},
		{
			MethodName: "ApplyJob",
			Handler:    _ApiService_ApplyJob_Handler,
		},
		{
			MethodName: "HistoryJoin",
			Handler:    _ApiService_HistoryJoin_Handler,
		},
		{
			MethodName: "CheckIsOkApplication",
			Handler:    _ApiService_CheckIsOkApplication_Handler,
		},
		{
			MethodName: "Pay",
			Handler:    _ApiService_Pay_Handler,
		},
		{
			MethodName: "GetAllOrderBySchedule",
			Handler:    _ApiService_GetAllOrderBySchedule_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _ApiService_GetContent_Handler,
		},
		{
			MethodName: "GetAllIncome",
			Handler:    _ApiService_GetAllIncome_Handler,
		},
		{
			MethodName: "GetIncomeBySchedule",
			Handler:    _ApiService_GetIncomeBySchedule_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _ApiService_GetBalance_Handler,
		},
		{
			MethodName: "GetAllMoney",
			Handler:    _ApiService_GetAllMoney_Handler,
		},
		{
			MethodName: "ManageContract",
			Handler:    _ApiService_ManageContract_Handler,
		},
		{
			MethodName: "CheckContract",
			Handler:    _ApiService_CheckContract_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _ApiService_ReloadConfig_Handler,
		},
		{
			MethodName: "ReloadDeploy",
			Handler:    _ApiService_ReloadDeploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0xd6, 0xcd, 0xb2, 0x74, 0x1c, 0xd9, 0xc9, 0xc4, 0x8e, 0x65, 0x26, 0x08, 0x9c, 0xf9, 0x7f,
	0x34, 0x4e, 0x5b, 0x24, 0x85, 0xd3, 0x4d, 0x11, 0xa0, 0x85, 0x6c, 0x27, 0x8e, 0x95, 0x38, 0x16,
	0x28, 0x07, 0xbd, 0x64, 0x61, 0x50, 0xd4, 0xd8, 0x66, 0x23, 0x73, 0x28, 0x92, 0x2e, 0xa0, 0xee,
	0xfa, 0x12, 0x05, 0xfa, 0x10, 0x45, 0x77, 0x7d, 0x80, 0xee, 0xba, 0x6c, 0xd7, 0x7d, 0x98, 0x62,
	0x6e, 0xe2, 0x0c, 0x49, 0x97, 0x4a, 0x63, 0xb8, 0x2b, 0x71, 0xce, 0x99, 0xf9, 0xe6, 0x3b, 0x67,
	0xe6, 0x5c, 0x46, 0xd0, 0x74, 0x02, 0xef, 0x61, 0x10, 0xd2, 0x98, 0xa2, 0x06, 0xff, 0x71, 0xe9,
	0xc8, 0x6a, 0xd2, 0xc1, 0xb7, 0x42, 0x88, 0xd7, 0xa0, 0x6a, 0x93, 0x31, 0x42, 0x50, 0xf3, 0x9d,
	0x33, 0xd2, 0x2e, 0xaf, 0x97, 0x37, 0x9a, 0x36, 0xff, 0xc6, 0xeb, 0x50, 0xb3, 0x49, 0x14, 0xa0,
	0x36, 0xcc, 0x9f, 0x91, 0x28, 0x72, 0x4e, 0x94, 0x5a, 0x0d, 0xf1, 0xa7, 0x70, 0xdd, 0x26, 0xe3,
	0x5d, 0x12, 0x3f, 0x8d, 0x4f, 0xb7, 0x9c, 0x91, 0xe3, 0xbb, 0x04, 0xad, 0xc3, 0xc2, 0xeb, 0x88,
	0x84, 0x9d, 0xe1, 0x30, 0x24, 0x51, 0x24, 0x57, 0xe8, 0x22, 0xbc, 0x0f, 0x37, 0x18, 0xae, 0xb9,
	0xec, 0x2e, 0x40, 0x3f, 0x76, 0xe2, 0xf3, 0x68, 0x9b, 0x0e, 0xc5, 0x3e, 0x2d, 0x5b, 0x93, 0x30,
	0x12, 0x72, 0x6a, 0xbb, 0x22, 0x48, 0xc8, 0x21, 0x7e, 0x00, 0x0b, 0x36, 0x19, 0xdb, 0xe4, 0xc4,
	0x8b, 0x62, 0x12, 0x22, 0x0b, 0x1a, 0x3d, 0x27, 0x8a, 0xbe, 0xa4, 0xe1, 0x50, 0x6e, 0x3e, 0x1d,
	0xe3, 0x1f, 0xcb, 0x70, 0x8d, 0x6d, 0x3d, 0x9d, 0x5c, 0xb4, 0x6b, 0xca, 0x98, 0x4a, 0xc6, 0x18,
	0x63, 0xbb, 0xaa, 0xb9, 0x1d, 0xda, 0x80, 0xa5, 0x8e, 0xeb, 0xd2, 0x73, 0x3f, 0xde, 0x21, 0x91,
	0x1b, 0x7a, 0x03, 0xd2, 0xae, 0xf1, 0x29, 0x69, 0x31, 0xfe, 0xa5, 0x0c, 0xf3, 0x36, 0x19, 0x6f,
	0x39, 0xfe, 0x90, 0x1d, 0xc5, 0x2b, 0xed, 0x28, 0xd8, 0xf7, 0x0c, 0x3c, 0x10, 0xd4, 0x6c, 0x3a,
	0x22, 0x92, 0x03, 0xff, 0x36, 0xb8, 0xd5, 0x52, 0xdc, 0x96, 0x61, 0xae, 0x77, 0x4a, 0x7d, 0xd2,
	0x9e, 0xe3, 0x0a, 0x31, 0xc8, 0x63, 0x5c, 0xcf, 0x67, 0xfc, 0x21, 0x34, 0x98, 0x27, 0x39, 0xe3,
	0x02, 0x2f, 0xe2, 0xc7, 0xb0, 0x64, 0x93, 0xf1, 0xf6, 0x29, 0x71, 0xdf, 0x4a, 0x98, 0x19, 0x6e,
	0xc9, 0xaf, 0x65, 0x76, 0xb9, 0xa2, 0xc0, 0x58, 0x56, 0x74, 0x5e, 0xca, 0x77, 0x15, 0xcd, 0x77,
	0x57, 0xed, 0x99, 0x3f, 0xcb, 0xd0, 0xb2, 0xc9, 0xb8, 0xef, 0x9e, 0x92, 0xe1, 0xf9, 0xc8, 0xf3,
	0x4f, 0x8a, 0x8d, 0x35, 0xf8, 0x54, 0x8a, 0x6f, 0x51, 0x35, 0x77, 0x67, 0x16, 0x23, 0xdb, 0xf4,
	0x2c, 0x70, 0xfc, 0x89, 0x34, 0x4a, 0x0d, 0xd1, 0x3d, 0xa8, 0x75, 0xe9, 0x20, 0x6a, 0xcf, 0xad,
	0x57, 0x37, 0x16, 0x36, 0x5b, 0x0f, 0x55, 0x26, 0x78, 0xd8, 0xa5, 0x03, 0x9b, 0xab, 0xd0, 0x1d,
	0x68, 0x1e, 0x7a, 0x67, 0xa4, 0x1f, 0x3b, 0x67, 0x01, 0x37, 0xad, 0x6a, 0x27, 0x02, 0xdc, 0x83,
	0x45, 0x76, 0x18, 0x9a, 0x51, 0x45, 0x47, 0x71, 0x17, 0xa0, 0x4b, 0x07, 0xe6, 0x8d, 0xd5, 0x24,
	0xf8, 0xa7, 0x32, 0x80, 0x4d, 0xc6, 0xcf, 0x3c, 0x7f, 0xd8, 0xa5, 0x83, 0x2b, 0xf3, 0xd1, 0xff,
	0x60, 0x6e, 0x7f, 0xd2, 0xa5, 0x03, 0xee, 0xa1, 0x8c, 0x2b, 0x84, 0x0e, 0xef, 0xb1, 0x94, 0x12,
	0x05, 0x8a, 0x5b, 0x91, 0xa9, 0x16, 0x34, 0x9e, 0x3b, 0xd1, 0x29, 0xd7, 0x4a, 0x66, 0x6a, 0x8c,
	0xff, 0x28, 0x43, 0xdd, 0x26, 0xe3, 0x9e, 0x33, 0xb9, 0x32, 0x13, 0x97, 0x61, 0x6e, 0x9f, 0xfa,
	0x44, 0x5c, 0x82, 0x9a, 0x2d, 0x06, 0xe8, 0x01, 0xbb, 0x1c, 0x7e, 0x4c, 0xfc, 0x98, 0x5f, 0xec,
	0x85, 0xcd, 0xa5, 0xc4, 0xf4, 0x83, 0x70, 0x48, 0x42, 0x5b, 0xe9, 0x53, 0x47, 0x57, 0xcf, 0x1c,
	0xdd, 0x11, 0x4b, 0x56, 0x51, 0xc0, 0x6c, 0x9a, 0x21, 0x6d, 0x73, 0xf0, 0x3d, 0x61, 0x50, 0xcb,
	0x56, 0x43, 0xc3, 0x69, 0xd5, 0x94, 0xd3, 0xfe, 0x92, 0x21, 0x44, 0x62, 0x45, 0xe9, 0x0a, 0x43,
	0x48, 0xf1, 0x95, 0x21, 0xa4, 0xf8, 0x5e, 0xa2, 0xff, 0xba, 0x32, 0x98, 0x12, 0xf3, 0xde, 0xd1,
	0x8d, 0x09, 0x2d, 0xfc, 0x96, 0x7b, 0x6a, 0xf7, 0x5d, 0x3c, 0x75, 0x21, 0x58, 0x8a, 0x78, 0x35,
	0x43, 0xfc, 0x8d, 0x20, 0xbe, 0x3b, 0x3b, 0xf1, 0x07, 0x30, 0xef, 0x4a, 0xaf, 0x55, 0x2e, 0xf0,
	0x9a, 0xd4, 0xe3, 0x90, 0x81, 0x73, 0x4b, 0x1c, 0xbf, 0x13, 0x04, 0xa3, 0x59, 0x02, 0x66, 0x1d,
	0x16, 0x64, 0x8a, 0xd3, 0xd2, 0xbe, 0x2e, 0x32, 0xd3, 0x9a, 0xb0, 0x48, 0x4b, 0x6b, 0x87, 0xac,
	0x32, 0x09, 0x83, 0xd4, 0xa6, 0x45, 0x16, 0xa9, 0x54, 0x5a, 0xb9, 0x30, 0x95, 0xe2, 0xb1, 0x3a,
	0x13, 0x91, 0x2e, 0xc9, 0x15, 0x18, 0x32, 0x98, 0x9e, 0x8c, 0xda, 0xb3, 0xc8, 0x8e, 0x4f, 0xa0,
	0x29, 0xb3, 0x39, 0x51, 0xc6, 0xa0, 0xc4, 0x18, 0xa5, 0xb2, 0x93, 0x49, 0xf8, 0x6b, 0x65, 0xd6,
	0xcc, 0xad, 0x1e, 0xfa, 0x00, 0x16, 0x25, 0x1f, 0xb3, 0x10, 0xa4, 0xa4, 0xf8, 0xd9, 0x94, 0xfe,
	0xac, 0xfd, 0xe0, 0x34, 0xc9, 0x55, 0xb4, 0x24, 0x87, 0xdf, 0xc0, 0xaa, 0xea, 0x34, 0xf6, 0xa2,
	0x83, 0xb7, 0xec, 0x44, 0x3d, 0xd7, 0x89, 0x3d, 0xea, 0xcf, 0x40, 0xb6, 0xa8, 0x62, 0x7d, 0x05,
	0xed, 0x69, 0x43, 0x92, 0x46, 0x2f, 0xa2, 0x7b, 0x07, 0x9a, 0x5e, 0xc4, 0x17, 0x10, 0x11, 0x75,
	0x0d, 0x3b, 0x11, 0xe0, 0x1f, 0xca, 0xac, 0x25, 0x1e, 0xef, 0x3b, 0xbe, 0x73, 0x42, 0x58, 0x68,
	0x85, 0x8e, 0x3b, 0x4b, 0x24, 0x63, 0xb8, 0xa6, 0x66, 0xb3, 0xdc, 0x29, 0x7d, 0x61, 0xc8, 0xd0,
	0x75, 0xa8, 0xf6, 0x42, 0x96, 0xef, 0xaa, 0x1b, 0x4d, 0x9b, 0x7d, 0x32, 0xd7, 0x75, 0x8e, 0x63,
	0x12, 0xb6, 0x6b, 0x5c, 0x26, 0x06, 0xb8, 0x07, 0x88, 0x59, 0x97, 0xe2, 0xf0, 0x3e, 0xa5, 0xef,
	0x73, 0xfe, 0x3a, 0xe0, 0xee, 0x9a, 0xe2, 0xb5, 0x61, 0xde, 0xb4, 0x47, 0x0d, 0x19, 0xcf, 0x17,
	0xf2, 0x38, 0x9b, 0x36, 0xfb, 0xc4, 0x07, 0xe2, 0x9d, 0x60, 0x02, 0xbc, 0x0f, 0xa1, 0x03, 0xfe,
	0x52, 0x60, 0x31, 0x12, 0x3b, 0xc7, 0xc7, 0x97, 0x70, 0x23, 0x8e, 0xc4, 0x73, 0x62, 0x8a, 0x58,
	0x44, 0xee, 0x11, 0xd4, 0xf9, 0x44, 0x15, 0x70, 0xab, 0x49, 0xc0, 0x45, 0x32, 0xcc, 0xb8, 0xde,
	0x96, 0xd3, 0xf0, 0x3a, 0xeb, 0xb2, 0xc7, 0x2f, 0xe9, 0x89, 0xe7, 0x27, 0x7d, 0x69, 0x59, 0xeb,
	0x4b, 0xf1, 0xef, 0x65, 0x68, 0x32, 0x0e, 0x62, 0xce, 0x7f, 0xd7, 0x1f, 0x6b, 0x07, 0x5b, 0x37,
	0x0f, 0x36, 0xa7, 0xf8, 0xce, 0xe7, 0x77, 0xce, 0xb6, 0xaa, 0x00, 0x9d, 0xd1, 0x88, 0x17, 0x87,
	0x4b, 0x38, 0xa2, 0xd1, 0x34, 0xc3, 0x4f, 0x41, 0x8b, 0x9c, 0x74, 0x1f, 0xea, 0x7c, 0xa2, 0x3a,
	0xa5, 0x4c, 0xc9, 0x92, 0x6a, 0x76, 0x65, 0xfb, 0xe7, 0x67, 0xdc, 0x71, 0x65, 0x9b, 0x7d, 0xe2,
	0x43, 0xcd, 0x02, 0xd1, 0x76, 0xa5, 0x12, 0x7b, 0x39, 0x9b, 0xd8, 0x0b, 0xdf, 0x76, 0x78, 0x5b,
	0xb7, 0x41, 0xc0, 0x16, 0xd9, 0x20, 0xa9, 0x55, 0x12, 0x6a, 0x2f, 0x39, 0xb5, 0xe7, 0x5e, 0x14,
	0xd3, 0x70, 0xd2, 0xa5, 0x9e, 0x3f, 0x5b, 0xa7, 0xa0, 0x1e, 0x14, 0x15, 0xe3, 0x41, 0xa1, 0x0a,
	0xa7, 0x0e, 0x77, 0x09, 0x85, 0xf3, 0x35, 0x7f, 0x28, 0x0a, 0x3b, 0xf7, 0x7c, 0x97, 0x0a, 0xef,
	0xbc, 0xb7, 0xff, 0xde, 0x88, 0x97, 0xa4, 0x81, 0x7b, 0x59, 0x97, 0x00, 0x7f, 0x0f, 0xb7, 0x04,
	0x67, 0x01, 0xbc, 0x35, 0x51, 0x05, 0xf3, 0x32, 0xa8, 0x17, 0x56, 0xfd, 0x55, 0x69, 0x58, 0x66,
	0xf3, 0x4b, 0xb3, 0xef, 0xb7, 0x0a, 0xb4, 0xb6, 0x6d, 0x32, 0xa2, 0xce, 0x70, 0x9b, 0xfa, 0xc7,
	0xde, 0x09, 0xba, 0x0f, 0x4b, 0x07, 0x01, 0x09, 0x9d, 0x98, 0x1c, 0xc5, 0xde, 0x19, 0xa1, 0xe7,
	0xb1, 0xc4, 0x5f, 0x94, 0xe2, 0x43, 0x21, 0x65, 0xe5, 0xe9, 0x25, 0x75, 0x9d, 0x91, 0x69, 0x9f,
	0x21, 0x63, 0xd9, 0xa7, 0x47, 0xc3, 0x58, 0x65, 0x1f, 0xf6, 0xcd, 0xb8, 0x77, 0x5c, 0x57, 0xad,
	0x12, 0xf9, 0x47, 0x93, 0x30, 0xfd, 0xd3, 0xf8, 0x54, 0xe9, 0x45, 0x1a, 0xd2, 0x24, 0xe8, 0x16,
	0xd4, 0xf7, 0x02, 0x77, 0xc7, 0x0b, 0x65, 0x2a, 0x92, 0x23, 0x96, 0xd5, 0xfa, 0x24, 0xfc, 0x8e,
	0x77, 0xbe, 0x22, 0x05, 0x4d, 0xc7, 0x0c, 0x53, 0x94, 0xbe, 0x90, 0x55, 0xa1, 0x86, 0xc0, 0x4c,
	0x24, 0xe8, 0xff, 0xd0, 0x92, 0xa3, 0xde, 0x69, 0xe8, 0x44, 0xa4, 0xdd, 0xe4, 0x53, 0x4c, 0x21,
	0xdb, 0xf9, 0x05, 0x99, 0xb0, 0x9d, 0x41, 0xec, 0x2c, 0x46, 0x78, 0x09, 0x5a, 0x7d, 0xdd, 0x87,
	0x78, 0x7b, 0xea, 0xd4, 0x1d, 0x12, 0x8c, 0xe8, 0xe4, 0x1f, 0x0a, 0x23, 0xd3, 0x88, 0x44, 0xa9,
	0x82, 0x50, 0x0e, 0x35, 0x54, 0x01, 0xb2, 0xf9, 0x73, 0x0b, 0xa0, 0x13, 0x78, 0xcc, 0x28, 0xcf,
	0x25, 0xe8, 0x23, 0x68, 0xf4, 0x9d, 0xc9, 0x73, 0x32, 0x1a, 0x51, 0xa4, 0xc5, 0x9b, 0x4d, 0xc6,
	0xd6, 0xa2, 0x3e, 0x8c, 0x02, 0x5c, 0x42, 0x4f, 0x58, 0xa9, 0x91, 0x7f, 0x8b, 0xad, 0x18, 0x93,
	0x95, 0xd8, 0xba, 0x65, 0x2e, 0x52, 0x72, 0x5c, 0x42, 0x8f, 0xa0, 0xc6, 0xff, 0x09, 0xba, 0x61,
	0x2c, 0x64, 0x22, 0x0b, 0x99, 0x8b, 0x98, 0x0c, 0x97, 0xd0, 0x26, 0xcc, 0x89, 0x8a, 0x65, 0xa8,
	0x45, 0xa5, 0xb3, 0x6e, 0x9a, 0x4b, 0xb8, 0x10, 0x97, 0xd0, 0x2e, 0x5c, 0x33, 0xfe, 0x0c, 0x5a,
	0x33, 0x96, 0xea, 0x2a, 0xcb, 0x32, 0x11, 0x74, 0x1d, 0x2e, 0xa1, 0x2e, 0xb4, 0xcc, 0x3f, 0x1f,
	0x8d, 0xe9, 0xe6, 0xff, 0x99, 0xd6, 0x6d, 0x13, 0xca, 0x50, 0xe2, 0x12, 0xda, 0x82, 0x85, 0xbe,
	0x6a, 0xba, 0x47, 0x04, 0xad, 0x1a, 0x48, 0xc9, 0xdf, 0x25, 0x56, 0xdb, 0x84, 0x49, 0x34, 0x02,
	0x63, 0xf7, 0x42, 0x8c, 0xa4, 0xa5, 0x4f, 0x63, 0x24, 0x1a, 0x5c, 0x42, 0x1d, 0x00, 0xf1, 0x8a,
	0xe1, 0xb9, 0xf8, 0x5f, 0x41, 0x3c, 0x81, 0x06, 0x4b, 0x91, 0xfc, 0x15, 0xb4, 0x92, 0x01, 0x60,
	0x0d, 0x49, 0xfa, 0x06, 0x28, 0x39, 0x2e, 0xa1, 0x2f, 0xa0, 0xbe, 0x4b, 0xe2, 0x2e, 0x1d, 0xa0,
	0x76, 0x7a, 0xa9, 0x7a, 0x5a, 0x59, 0x6b, 0x99, 0xd5, 0x4a, 0x85, 0x4b, 0xe8, 0x33, 0x68, 0xf0,
	0x4f, 0x06, 0xb1, 0x6c, 0x40, 0xc8, 0xbf, 0x61, 0xac, 0x15, 0x73, 0xb9, 0x14, 0xe3, 0x12, 0xda,
	0x81, 0x05, 0xbd, 0x10, 0x99, 0x04, 0x34, 0x4d, 0x9a, 0x80, 0xa6, 0xc2, 0x25, 0x74, 0x04, 0xcb,
	0xb9, 0xad, 0xfd, 0xbd, 0xec, 0x35, 0x4b, 0x4d, 0xb1, 0x70, 0xce, 0x75, 0x4b, 0xcd, 0xc1, 0x25,
	0xf4, 0x31, 0x54, 0x7b, 0xce, 0x04, 0x5d, 0x37, 0xf0, 0x7a, 0xce, 0xc4, 0xba, 0x61, 0x2e, 0xef,
	0x39, 0xcc, 0x1f, 0xaf, 0x60, 0x45, 0x6b, 0x5a, 0xb4, 0xcc, 0x9e, 0xf1, 0xaf, 0x9a, 0x93, 0xe3,
	0x5f, 0xa5, 0x4a, 0x2e, 0x88, 0x7c, 0xb7, 0x67, 0x2e, 0x88, 0x54, 0xe4, 0x5c, 0x10, 0xa9, 0x11,
	0x01, 0x68, 0xd4, 0xd0, 0xb5, 0x1c, 0x26, 0x42, 0x95, 0x0e, 0x40, 0x5d, 0x87, 0x4b, 0xe8, 0x1b,
	0xb8, 0x99, 0x5b, 0x30, 0xd3, 0x78, 0xe9, 0x19, 0xd6, 0xbd, 0x0c, 0x6c, 0x06, 0x44, 0xd8, 0xa9,
	0x22, 0x3b, 0x63, 0xa7, 0x0a, 0xeb, 0xac, 0x9d, 0x49, 0x4c, 0xef, 0xf0, 0x78, 0x9c, 0xf6, 0x5a,
	0x79, 0x0e, 0xe7, 0x9a, 0x7c, 0x87, 0x8b, 0x97, 0x68, 0x09, 0xed, 0xc3, 0x62, 0xea, 0x31, 0x65,
	0xa4, 0x92, 0xd4, 0x6b, 0xcf, 0xba, 0x63, 0x62, 0x99, 0x5a, 0x91, 0xb4, 0xcc, 0x97, 0x90, 0x95,
	0xbd, 0x97, 0x53, 0xb0, 0xdb, 0x39, 0x17, 0x52, 0xc3, 0xda, 0x62, 0xef, 0x16, 0xad, 0xa2, 0x6b,
	0x5e, 0x32, 0x4a, 0xbd, 0xa5, 0x29, 0xcc, 0xfa, 0xa5, 0x61, 0xc8, 0x02, 0x96, 0xc5, 0x10, 0x8a,
	0x1c, 0x0c, 0xa1, 0xc0, 0xa5, 0x41, 0x9d, 0x6b, 0x1e, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf0,
	0xd8, 0xca, 0xc2, 0xa5, 0x1a, 0x00, 0x00,
}
