// Code generated by protoc-gen-go. DO NOT EDIT.
// source: obj.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 职位对象
type Job struct {
	JobAddress string `protobuf:"bytes,1,opt,name=JobAddress" json:"JobAddress,omitempty"`
	Role       string `protobuf:"bytes,2,opt,name=Role" json:"Role,omitempty"`
	Count      uint32 `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	Radio      uint64 `protobuf:"varint,4,opt,name=Radio" json:"Radio,omitempty"`
	// uint64 IssueRadio = 5;
	Company    string   `protobuf:"bytes,6,opt,name=Company" json:"Company,omitempty"`
	TimeStamp  int64    `protobuf:"varint,7,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	HasApply   bool     `protobuf:"varint,8,opt,name=HasApply" json:"HasApply,omitempty"`
	JobId      int32    `protobuf:"varint,9,opt,name=JobId" json:"JobId,omitempty"`
	FatherAddr string   `protobuf:"bytes,10,opt,name=FatherAddr" json:"FatherAddr,omitempty"`
	WhiteList  []string `protobuf:"bytes,11,rep,name=WhiteList" json:"WhiteList,omitempty"`
	WhiteName  string   `protobuf:"bytes,12,opt,name=WhiteName" json:"WhiteName,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Job) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

func (m *Job) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Job) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Job) GetRadio() uint64 {
	if m != nil {
		return m.Radio
	}
	return 0
}

func (m *Job) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Job) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Job) GetHasApply() bool {
	if m != nil {
		return m.HasApply
	}
	return false
}

func (m *Job) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *Job) GetFatherAddr() string {
	if m != nil {
		return m.FatherAddr
	}
	return ""
}

func (m *Job) GetWhiteList() []string {
	if m != nil {
		return m.WhiteList
	}
	return nil
}

func (m *Job) GetWhiteName() string {
	if m != nil {
		return m.WhiteName
	}
	return ""
}

// 工作单位
type Unit struct {
	Role      string `protobuf:"bytes,1,opt,name=Role" json:"Role,omitempty"`
	Company   string `protobuf:"bytes,2,opt,name=Company" json:"Company,omitempty"`
	Location  string `protobuf:"bytes,3,opt,name=Location" json:"Location,omitempty"`
	StartTime uint32 `protobuf:"varint,4,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime   uint32 `protobuf:"varint,5,opt,name=EndTime" json:"EndTime,omitempty"`
}

func (m *Unit) Reset()                    { *m = Unit{} }
func (m *Unit) String() string            { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()               {}
func (*Unit) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Unit) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Unit) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Unit) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Unit) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Unit) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

// 排班
type Schedule struct {
	Jobaddr       string `protobuf:"bytes,1,opt,name=Jobaddr" json:"Jobaddr,omitempty"`
	Jobs          []*Job `protobuf:"bytes,2,rep,name=Jobs" json:"Jobs,omitempty"`
	TimeStamp     int64  `protobuf:"varint,3,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	CompanyName   string `protobuf:"bytes,4,opt,name=CompanyName" json:"CompanyName,omitempty"`
	CompanyRatio  int64  `protobuf:"varint,5,opt,name=CompanyRatio" json:"CompanyRatio,omitempty"`
	FatherAddress string `protobuf:"bytes,6,opt,name=FatherAddress" json:"FatherAddress,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Schedule) GetJobaddr() string {
	if m != nil {
		return m.Jobaddr
	}
	return ""
}

func (m *Schedule) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *Schedule) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Schedule) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *Schedule) GetCompanyRatio() int64 {
	if m != nil {
		return m.CompanyRatio
	}
	return 0
}

func (m *Schedule) GetFatherAddress() string {
	if m != nil {
		return m.FatherAddress
	}
	return ""
}

// 申请人信息
type ScheduleStaff struct {
	StaffAddr  string `protobuf:"bytes,1,opt,name=StaffAddr" json:"StaffAddr,omitempty"`
	Role       string `protobuf:"bytes,2,opt,name=Role" json:"Role,omitempty"`
	Ratio      uint64 `protobuf:"varint,3,opt,name=Ratio" json:"Ratio,omitempty"`
	JobId      int64  `protobuf:"varint,4,opt,name=JobId" json:"JobId,omitempty"`
	FatherAddr string `protobuf:"bytes,5,opt,name=FatherAddr" json:"FatherAddr,omitempty"`
}

func (m *ScheduleStaff) Reset()                    { *m = ScheduleStaff{} }
func (m *ScheduleStaff) String() string            { return proto.CompactTextString(m) }
func (*ScheduleStaff) ProtoMessage()               {}
func (*ScheduleStaff) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ScheduleStaff) GetStaffAddr() string {
	if m != nil {
		return m.StaffAddr
	}
	return ""
}

func (m *ScheduleStaff) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ScheduleStaff) GetRatio() uint64 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

func (m *ScheduleStaff) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *ScheduleStaff) GetFatherAddr() string {
	if m != nil {
		return m.FatherAddr
	}
	return ""
}

// 订单信息
type Order struct {
	Table      uint32  `protobuf:"varint,1,opt,name=Table" json:"Table,omitempty"`
	TimeStamp  int64   `protobuf:"varint,2,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	Money      float64 `protobuf:"fixed64,3,opt,name=Money" json:"Money,omitempty"`
	OrderId    string  `protobuf:"bytes,4,opt,name=OrderId" json:"OrderId,omitempty"`
	Content    string  `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	GetMoney_  float64 `protobuf:"fixed64,6,opt,name=GetMoney" json:"GetMoney,omitempty"`
	JobAddress string  `protobuf:"bytes,7,opt,name=JobAddress" json:"JobAddress,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Order) GetTable() uint32 {
	if m != nil {
		return m.Table
	}
	return 0
}

func (m *Order) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Order) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Order) GetGetMoney_() float64 {
	if m != nil {
		return m.GetMoney_
	}
	return 0
}

func (m *Order) GetJobAddress() string {
	if m != nil {
		return m.JobAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "protocol.Job")
	proto.RegisterType((*Unit)(nil), "protocol.Unit")
	proto.RegisterType((*Schedule)(nil), "protocol.Schedule")
	proto.RegisterType((*ScheduleStaff)(nil), "protocol.scheduleStaff")
	proto.RegisterType((*Order)(nil), "protocol.Order")
}

func init() { proto.RegisterFile("obj.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4b, 0x8e, 0xd3, 0x40,
	0x10, 0x55, 0xfb, 0x93, 0xd8, 0x95, 0xf1, 0xa6, 0x35, 0x8b, 0xd6, 0x08, 0x21, 0x63, 0xb1, 0xf0,
	0x2a, 0x0b, 0x38, 0x41, 0x18, 0xf1, 0xb3, 0x06, 0x90, 0x3a, 0x83, 0x58, 0xb7, 0xe3, 0x8e, 0x62,
	0x94, 0xb8, 0x2d, 0xbb, 0xb3, 0xc8, 0x8e, 0x25, 0x1b, 0x4e, 0xc2, 0x29, 0x38, 0x02, 0x37, 0x42,
	0x5d, 0xed, 0x4f, 0x6c, 0x31, 0xab, 0xe4, 0xbd, 0x92, 0xab, 0xea, 0xbd, 0x7a, 0x0d, 0xa1, 0xca,
	0xbf, 0xaf, 0xeb, 0x46, 0x69, 0x45, 0x03, 0xfc, 0xd9, 0xa9, 0x63, 0xf2, 0xdb, 0x01, 0x37, 0x53,
	0x39, 0x7d, 0x0e, 0x90, 0xa9, 0x7c, 0x53, 0x14, 0x8d, 0x6c, 0x5b, 0x46, 0x62, 0x92, 0x86, 0xfc,
	0x8a, 0xa1, 0x14, 0x3c, 0xae, 0x8e, 0x92, 0x39, 0x58, 0xc1, 0xff, 0xf4, 0x16, 0xfc, 0x7b, 0x75,
	0xae, 0x34, 0x73, 0x63, 0x92, 0x46, 0xdc, 0x02, 0xc3, 0x72, 0x51, 0x94, 0x8a, 0x79, 0x31, 0x49,
	0x3d, 0x6e, 0x01, 0x65, 0xb0, 0xbc, 0x57, 0xa7, 0x5a, 0x54, 0x17, 0xb6, 0xc0, 0x16, 0x3d, 0xa4,
	0xcf, 0x20, 0x7c, 0x2c, 0x4f, 0x72, 0xab, 0xc5, 0xa9, 0x66, 0xcb, 0x98, 0xa4, 0x2e, 0x1f, 0x09,
	0x7a, 0x07, 0xc1, 0x07, 0xd1, 0x6e, 0xea, 0xfa, 0x78, 0x61, 0x41, 0x4c, 0xd2, 0x80, 0x0f, 0xd8,
	0x4c, 0xca, 0x54, 0xfe, 0xb1, 0x60, 0x61, 0x4c, 0x52, 0x9f, 0x5b, 0x60, 0x94, 0xbc, 0x13, 0xfa,
	0x20, 0x1b, 0xb3, 0x3a, 0x03, 0xab, 0x64, 0x64, 0xcc, 0xbc, 0x6f, 0x87, 0x52, 0xcb, 0x87, 0xb2,
	0xd5, 0x6c, 0x15, 0xbb, 0x69, 0xc8, 0x47, 0x62, 0xa8, 0x7e, 0x16, 0x27, 0xc9, 0x6e, 0xf0, 0xe3,
	0x91, 0x48, 0x7e, 0x12, 0xf0, 0xbe, 0x56, 0xa5, 0x1e, 0xec, 0x20, 0x57, 0x76, 0x5c, 0x49, 0x74,
	0xa6, 0x12, 0xef, 0x20, 0x78, 0x50, 0x3b, 0xa1, 0x4b, 0x55, 0xa1, 0x57, 0x21, 0x1f, 0xb0, 0x19,
	0xb8, 0xd5, 0xa2, 0xd1, 0x46, 0x32, 0x5a, 0x16, 0xf1, 0x91, 0x30, 0x3d, 0xdf, 0x56, 0x05, 0xd6,
	0x7c, 0xac, 0xf5, 0x30, 0xf9, 0x4b, 0x20, 0xd8, 0xee, 0x0e, 0xb2, 0x38, 0xdb, 0xd1, 0x99, 0xca,
	0x85, 0x11, 0x6c, 0x37, 0xea, 0x21, 0x7d, 0x01, 0x5e, 0xa6, 0xf2, 0x96, 0x39, 0xb1, 0x9b, 0xae,
	0x5e, 0x45, 0xeb, 0xfe, 0xf0, 0xeb, 0x4c, 0xe5, 0x1c, 0x4b, 0xd3, 0x03, 0xb8, 0xf3, 0x03, 0xc4,
	0xb0, 0xea, 0x64, 0xa0, 0x25, 0x1e, 0xb6, 0xbf, 0xa6, 0x68, 0x02, 0x37, 0x1d, 0xe4, 0x46, 0x12,
	0x2e, 0xea, 0xf2, 0x09, 0x47, 0x5f, 0x42, 0x34, 0x9e, 0xc0, 0x24, 0xcc, 0x86, 0x60, 0x4a, 0x26,
	0xbf, 0x08, 0x44, 0x6d, 0xa7, 0x69, 0xab, 0xc5, 0x7e, 0xdf, 0xb9, 0xb3, 0xdf, 0x6f, 0x46, 0x69,
	0x23, 0xf1, 0x54, 0x28, 0xed, 0x1a, 0x6e, 0x1f, 0x3f, 0x33, 0x7f, 0x88, 0x8a, 0x87, 0xcb, 0xfd,
	0x37, 0x2a, 0xfe, 0x3c, 0x2a, 0xc9, 0x1f, 0x02, 0xfe, 0x97, 0xa6, 0x90, 0x8d, 0xf9, 0xfe, 0x51,
	0xe4, 0xdd, 0xc1, 0x23, 0x6e, 0xc1, 0xd4, 0x39, 0x67, 0xee, 0xdc, 0x2d, 0xf8, 0x9f, 0x54, 0x25,
	0x2f, 0xb8, 0x09, 0xe1, 0x16, 0x98, 0x53, 0x61, 0xcb, 0x6e, 0x97, 0x90, 0xf7, 0xd0, 0xe6, 0xa7,
	0xd2, 0xb2, 0xd2, 0xdd, 0x2a, 0x3d, 0x34, 0xf9, 0x79, 0x2f, 0xb5, 0x6d, 0xb6, 0xc0, 0x66, 0x03,
	0x9e, 0x3d, 0xdc, 0xe5, 0xfc, 0xe1, 0xbe, 0x71, 0x7f, 0x10, 0x92, 0x2f, 0xf0, 0xec, 0xaf, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xd5, 0x05, 0xfb, 0x03, 0x04, 0x00, 0x00,
}
